package org.sibermatica.cosmoides;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author CiroZDP
 */
public class Cosmoides extends javax.swing.JFrame {

    public static final int BUILD_RELEASE = 0;
    public static final int BUILD_NIGHTLY = 1;

    /**
     * Creates new form Cosmoides
     */
    public Cosmoides() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cosmoides Launcher 2.5.0");
        setBackground(new java.awt.Color(38, 38, 38));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setName("main_container"); // NOI18N
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 110, 55));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("↑");
        jButton2.setBorder(null);
        jButton2.setEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(717, 362, 20, 55);

        jButton1.setBackground(new java.awt.Color(0, 137, 69));
        jButton1.setFont(getMinecraftTen().deriveFont(Font.PLAIN, 24));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DOWNLOAD");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 360, 280, 60);
        jButton1.getAccessibleContext().setAccessibleName("");

        jList1.setBackground(new java.awt.Color(32, 32, 32));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 32, 32), 6));
        jList1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Latest Release", "Latest Build" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCellRenderer(new MinecraftIconCellRenderer());
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jPanel1.add(jList1);
        jList1.setBounds(0, 0, 200, 630);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(getMinecraftFont().deriveFont(Font.PLAIN, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Downloading...");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 110, 620, 50);
        jLabel1.getAccessibleContext().setAccessibleName("");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setRequestFocusEnabled(false);
        jPanel2.add(jProgressBar1);
        jProgressBar1.setBounds(110, 180, 620, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(200, 40, 810, 310);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 30, 620, 360);

        jPanel3.setBackground(new java.awt.Color(66, 66, 66));
        jPanel3.setLayout(null);

        jLabel3.setFont(getMinecraftTen().deriveFont(Font.PLAIN, 28));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ChangeLog");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 10, 180, 50);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("- PS3: Now it works on real hardware!");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 60, 580, 30);

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 430, 710, 200);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Cosmoides Launcher 2.5.0");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jList1ValueChanged

    private String getBuildURLByNumber(int number) {
        if (number == BUILD_RELEASE) {
            return "https://cdn.classicube.net/client/release/win32/ClassiCube.exe";
        }
        return "suerte descargando esto!";
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (!jButton1.isEnabled())
            return;
        
        String path = String.join(File.separator, "classicube", "ClassiCube.exe");
        File file = new File(path);

        if (file.exists()) {
            jButton1.setText("PLAY");

            /*
             * Using ProcessBuilder instead of Runtime exec
             * should fix the issue #1 (Classicube crashes unless you close the launcher)
             */
            Thread classiCubeProcessThread = new Thread(() -> {
                try {
                    ProcessBuilder pb = new ProcessBuilder(path);
                    pb.directory(file.getParentFile()); // Fix issue #2 (Classicube selects current directory as default)
                    Process p = pb.start();
                    pb = null;
                    p = null;
                    System.gc();
                } catch (Exception ignored) {
                    JOptionPane.showMessageDialog(this, "Failed to start ClassiCube!", "Launcher Error", JOptionPane.ERROR_MESSAGE);
                }
            });

            classiCubeProcessThread.start();

            return;
        }

        Future<Void> future = DownloadHelper.download(getBuildURLByNumber(jList1.getSelectedIndex()), path);
        Runnable progressBarManagerRunnable = () -> {
            if (jPanel2.isVisible()) {
                return;
            }

            while (!future.isDone()) {
                jPanel2.setVisible(true);
                jButton1.setText("DOWNLOAD");
            }

            jPanel2.setVisible(false);
            jButton1.setText("PLAY");

            // Execute the button another time
            jButton1MouseClicked(null);
        };

        Thread progressBarManagerThread = new Thread(progressBarManagerRunnable);
        progressBarManagerThread.start();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (!jButton2.isEnabled())
            return;
        
        GameOptions.instance.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    public Font getMinecraftTen() {
        try {
            return Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/fonts/Minecraft-Ten-ed29a.otf"));
        } catch (Exception ignored) {
        }

        return new Font("Dialog", Font.PLAIN, 12);
    }

    public Font getMinecraftFont() {
        try {
            return Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/fonts/Mojangles.ttf"));
        } catch (Exception ignored) {
        }

        return new Font("Dialog", Font.PLAIN, 12);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        FlatLaf.setGlobalExtraDefaults( Collections.singletonMap( "@accentColor", "#FF9F0A" ) );
        FlatDarkLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cosmoides cosmoides = new Cosmoides();
                try {
                    List<String> iconPaths = new ArrayList<>();
                    for (int resolution = 16; resolution < 257; resolution *= 2) {
                        iconPaths.add("/icon/icon-" + resolution + ".png");
                    }

                    List<BufferedImage> icons = iconPaths.stream().map(path -> {
                        try {
                            return ImageIO.read(Cosmoides.class.getResourceAsStream(path));
                        } catch (Exception ignored) {
                            return null;
                        }
                    }).collect(Collectors.toList());

                    if (!icons.stream().anyMatch(o -> o == null)) {
                        cosmoides.setIconImages(icons);
                    }

                } catch (Exception ignored) {
                }

                File file = new File("classicube/ClassiCube.exe");
                if (file.exists())
                    file.delete();
                
                cosmoides.jPanel2.setVisible(false);
                cosmoides.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
